### ISSUE TITLE
Validation email on sign-up (before consent page)

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#103]
The client would like there to be a validation email to ensure that the communication method is correct

**Comment by Cleop** [comment]
@ellemindwave 

@SimonLab is currently working on an email notification that you created as an issue here: #31, is this a new issue or a repeat?

- **Do you mean verification rather than validation?**

The current notification will ensure that the user's communication method is correct as the user will be told on the site 'you will now receive a confirmation email' and if they do not receive this email then they can get in touch.

A verification email would be different because it would block the user from progressing with their sign up until it has been opened and the link within it has been clicked. This is technically more complex and may also deter users from progressing in what is already a long user sign up journey. Once the user has clicked the link they can then continue their journey and therefore if they didn't receive an email (and therefore the communication method was not correct) then again, they'd have to contact the team to sort this out.

Let me know if neither of these scenarios describes what you're referring to.

- When is 'on sign up'? After the whole sign up process is complete (ie. after Qualtrics)? or after you've entered your email address etc but before consent?

**Comment by Cleop** [comment]
This also relates to #12 

I think we need to clear up some of these issues that seem to be duplicates and also to be very explicit on the terminology being used because at the moment we are referring to notification/confirmation/validation and verification emails which may or may not have different meanings to those using them.

@ellemindwave please can you look at the issues and close any that are not being worked on yet but that are duplicates? Please can you also clarify any key term wording on them?

**Comment by ellemindwave** [comment]
@Cleop I have checked with the client and it seems the main purpose of this email is to check that the user has given a suitable form of communication. Therefore, it makes sense to keep it how it is and not divert them from the page in order to go into their inbox. 
Thanks for clearing this up, and apologies about the terminology used! 

You are correct, I mean a validation email, and not a verification email. We just need to know that the user has provided a correct means for us to contact them.

**Comment by Cleop** [comment]
Thanks @ellemindwave for clarifying. 

I believe this issue is a duplicate of #31 `Notification email to user when registration is complete`, as @SimonLab has begun working on #31 already and it is the original issue can you close this one @ellemindwave?

You can always add the user story from this one to the other issue if you think it would be beneficial.

**Comment by ellemindwave** [comment]
@Cleop this is not a duplicate of #31 .

The validation email is sent to users at the very start, after you've entered your email address etc but before consent.

The #31 refers to a notification email that is sent once a user has completed the whole sign-up journey and their saliva kit has been received that their registration is complete (and they can now start consenting to projects etc)

**Comment by Cleop** [comment]
Sorry @ellemindwave, I thought it was because you didn't answer my question earlier when I asked: 

`When is 'on sign up'? After the whole sign up process is complete (ie. after Qualtrics)? or after you've entered your email address etc but before consent?`

Thanks for clarifying.

**Comment by SimonLab** [comment]
The functionality to send the email as soon as the user register is ready. We just need Amazon SES to authorise the application to send email to anyone. I apply this morning and we should get a response from Amazon soon

**Comment by Cleop** [comment]
@ellemindwave I believe this is a duplicate of : #12

**Comment by ellemindwave** [comment]
@Cleop It was a duplicate of #12 , I have closed issue #12 and this is now the only issue open for the  initial sign-up validation email

**Comment by SimonLab** [comment]
From Amazon: "Congratulations! After reviewing your case, we have increased your sending quota to 50,000 messages per day and your maximum send rate to 14 messages per second in AWS Region EU (Ireland). Your account has also been moved out of the sandbox, so you no longer need to verify recipient addresses"

**Comment by Cleop** [comment]
I've renamed this issue so that we can tell exactly what it is/ when it should occur without having to open it and read through the comments.

**Comment by ellemindwave** [comment]
👍
