### ISSUE TITLE
Generate Projects page content dynamically from Redcap

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#119]
**As a** user...
**I want to** be able to see the most up to date project information...
**so that** I can trust that I am consenting to exactly what I am reading when I read about projects.

The Projects page currently displays content on projects that have been hard-coded in. We now need to connect this page with the data on Redcap so that the content displays dynamically and users are always viewing the up to date content.

This will also make updating content easier for the RR staff.

**Comment by SimonLab** [comment]
If we remember correctly we think that the team had already define a structure in Redcap to store the projects. @ellemindwave do you know if it's possible to get a screenshot or the csv file of this structure?

**Comment by ellemindwave** [comment]
@SimonLab 
Yes, here is an example from the team of how a project page would look in Redcap.

They also raised these questions / points :
- Can the project name be filled in automatically from the website?
- The consent items will vary with each project based on their specific consents (also relates #116 )
- There may be other team actions and details added 

![image](https://cloud.githubusercontent.com/assets/26304634/24502169/8c6163ee-1544-11e7-9490-9a002615d3b9.png)

**Comment by Cleop** [comment]
Thanks @ellemindwave, this screenshot does not have a field for the project description info which is the info required in this issue. Is that field going to be in the same part of Redcap too (the team just don't use the field in their current working model)?

- Project descriptions content needed
- Redcap structure confirmation needed (regarding project description)

**Comment by SimonLab** [comment]
- "Can the project name be filled in automatically from the website?":

Is the idea is to allow the team to login in the application and create and define the project on the application instead of Redcap? If yes this implies to create a cms with user team authentication. I think the cms will be nice to have but I'm not sure if it's a high priority as it will take some time to implement and I think the team is already familiar with Redcap so it might just be quicker for them to create the projects in redcap? Are there any other reasons or features that will need to b handle by a cms?


- Project descriptions content needed & Redcap structure confirmation needed:

From the screenshot we can enhance the structure of the projects database in Redap to add the fields that we will need to display on the website (ex: description). Once the structure is defined we can create the documentation (can also create a screencast if needed) for the team to explain them how to add new project in Redcap with the right structure. The documentation and the user flow on how to create project will still need to be confirmed by the team. However if the team has already a detailed flow on how to create projects it might be better and quicker to understand it and implement it directly. Otherwise we can start to implement the Redcap structure with the new fields and get the feedback from the team, does this sounds good @ellemindwave @sarahwelton ?

**Comment by Cleop** [comment]
- We will do a first pass at this by creating a project name and project info/description fields whilst we await the exact confirmation of what should be included.

**Comment by ellemindwave** [comment]
@Cleop 
Here is a response on this from the client:

'We don't have a detailed flow on how to create projects as we don't post these online. We are happy to have the project description field added along with any other fields that need to be in place for content management. The only thing we thought of is whether these fields could be changed in the future if we decide we want to change how projects are advertised - e.g what fields are displayed etc? '

**Comment by ellemindwave** [comment]
This is also relevant to #118

**Comment by Cleop** [comment]
@Danwhy @SimonLab - will it be possible for the client to create additional project properties at a later date and for these to display on the site (in the same way that you have set up the consent page and new consent fields)?

**Comment by Cleop** [comment]
@ellemindwave I've spoken to the team. In order for us to answer whether extra fields could be added at a later date we would need to know more parameters:

- Where would these fields need to appear? (below or above the existing fields?)
- What kinds of fields would these be? (text fields or aerial buttons or something else?)

In theory if the team just wishes to add some extra info about a project, I don't see anything stopping them from simply adding that new info into the project description. Does this cover what you had in mind?

**Comment by ellemindwave** [comment]
@Cleop Thanks for this - Will check with the team

**Comment by ellemindwave** [comment]
@Cleop @Danwhy @SimonLab 
From the client:

'The other fields we were thinking might need to be added would be yes/no buttons and textboxes . Because we haven't done our recruitment this way before, it would nice to be able to change what we are putting on the projects page if we find we are needing to collecting more information. These fields would probably come before the consent items?

Also, the consent item content and number of items will change with each new project that comes through us, is that ok? '

**Comment by SimonLab** [comment]
Thanks @Cleop 
The yes/no questions can already be added dynamically from Redcap. For the input text we need to create a UI to be able to display them automatically on the page. I think this should be ok to implement
