### ISSUE TITLE
Changing saliva kit request copy

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#161]
Please put 'Thank you for requesting your saliva sample kit, you should receive it in the post shortly'

**Comment by ellemindwave** [comment]
@Danwhy This still says 'you should receive it in XX days'

![screen shot 2017-04-10 at 11 49 33](https://cloud.githubusercontent.com/assets/26304634/24858326/d167c026-1de3-11e7-9419-43b8c108f262.png)

**Comment by SimonLab** [comment]
I think the text has been changed on the notification page (the page displayed when the user has sent her address information):
![saliva-kit-notification](https://cloud.githubusercontent.com/assets/6057298/24861384/788f62e4-1df0-11e7-9377-bba9a55a4dc2.png)

Should we just display "Please provide your details so that we can send you a saliva kit" or also "You should receive it in the post shortly" under it?

**Comment by ellemindwave** [comment]
Ah yes, it has on that page 👍 
Once it is also updated on the saliva kit request I will close this issue. Thanks!
