### ISSUE TITLE
Notification to TTRR team when a user consents to a project

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#48]
As an admin, I want to be notified when someone consents to participating in any project so that I can inform the relevant Project Owner

**Comment by Cleop** [comment]
- As an admin, I want to receive an email notification when someone consents to participating in a project so that I can inform the relevant Project Owner

@ellemindwave What's the purpose of this email notification? Does the Project Owner then have to do something when a user joins a project?

Perhaps if this is just to help them monitor a project activity then this is a low priority issue because it's more of a 'nice to have' than a critical action shaper.

I wonder whether it might become an annoyance when the project scales because with hundreds/thousands of users and multiple projects potentially per person that could create one very full inbox!

**Comment by ellemindwave** [comment]
@Cleop The project owner does not have to do anything, it is just to keep them up to date with how many people have consented to their project. Whether or not the end up using a particular user's data is irrelevant. 
So in that respect, I think you are right in that it is relatively low priority and a 'nice to have'. 
It would certainly become annoying when the project scales, so maybe a weekly summary email would be more appropriate to get an idea of numbers. 
Towards the bottom of the pile priority wise right now anyway.

**Comment by SimonLab** [comment]
Each project defined in Redcap needs to have the email of the project owner. Sending a recap email at a certain time is the same logic/feature as #20 , so once this issue has been completed we will be able to implement this feature quicker.

**Comment by SimonLab** [comment]
The current message my imagination let me create:

    Hello,
    #{user.first_name} - #{user.ttrrid} has applied for the following project: #{project}

@ellemindwave have you got a better content for that email?

**Comment by ellemindwave** [comment]
@SimonLab Please can the copy throughout be changed from 'applied for' to 'consented to' ?
Other than that, the current copy for this notification email is fine for the time being 👍

**Comment by ellemindwave** [comment]
Thanks @SimonLab - please can I see a screenshot of what this email now looks like?

**Comment by SimonLab** [comment]
The email received when a user consent to a project:
![project-application-email](https://cloud.githubusercontent.com/assets/6057298/24907263/5a2933f2-1eb3-11e7-8282-79d25627c119.png)

**Comment by ellemindwave** [comment]
Awesome 👍
